#!/bin/bash
# Graudit - Rough code review tool using grep
# Written by Wireghoul - http://www.justanotherhacker.com
# Released under the GPL licence
set -e
set -o pipefail

VERSION='1.3'
grdir=`dirname $0`

# Default values
context=1
color='always'
database="$grdir/signatures/default.db"
separator='##############################################'

if [ ! -x /bin/grep ]; then
    echo "/bin/grep not found"
    exit 2
fi

version () {
    echo "Graudit version: $VERSION"
}

usage () {
    cat <<EOU
Usage: graudit [opts] /path/to/scan

OPTIONS
  -h show this message
  -v show version number
  -d database to use
  -c number of lines of context to display
  -z supress colors

Database is one of php, perl, rough or default, not providing a database will use default
/path is the path to the file or directory to audit
EOU
}

while getopts "hvzd:c:" opt; do
    case $opt in
        h)
            usage
            exit 1
        ;;
        v)
            version
            exit 0
        ;;
        z)
            color='none'
        ;;
        c)
            context="$OPTARG"
        ;;
        d)
            sigdb="$OPTARG"
            if [ "$sigdb" == '-' ]; then
                database='-'
            elif [ "$sigdb" == '*' ]; then
                database="$grdir/signatures/*"
            elif [ -f "$sigdb" ]; then
                database="$sigdb"
            else
                database="$grdir/signatures/$sigdb.db"
            fi
        ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            usage
            exit 2
        ;;
    esac
done
#Remove arguments from $@
shift $((OPTIND-1))

if [ -z "$1" ]; then
        usage
        exit 2
fi

# -R is recursive
# -H prints the name of the file
# -C prints # lines of context before and after the match
# -E uses extended regexp
# -f specifies the rule file (signature database)
# -n prints the line number

################################################################################
# START - Issue 1 - http://github.com/wireghoul/graudit/issues#issue/1
# grep version issue
# Modified 20091104 - Gary Wilson (gary.wilson the-at-thing of-networks the-dot-thing co the-dot-thing uk)

# Check client grep version
GREP_VERSION=`grep --version | grep "GNU grep" | sed -e "s/grep (GNU grep) //g;s/\.//g"`
if [ $GREP_VERSION -lt "253" ]; then
  grep --color=$color \
       -n -R -H -C $context -E \
       -f "$database" "$@" \
      | sed -e"s/--/$separator/"  | grep -v '/\.svn/.*[0-9][-:]\|/.cvs/.*[0-9][-:]\|/.git/.*[0-9][-:]' | sed '/#$/!b;N;/#$/d'
else
  grep --color=$color \
          --exclude-dir=.svn \
          --exclude-dir=.cvs \
          --exclude-dir=.git \
          -n -R -H -C $context -E \
          -f "$database" "$@" \
          | sed -e"s/--/$separator/"
fi

# END - Issue 1
################################################################################

exit $?
